"""
Cloud Run chat service: thin API wrapper around rag_chain.py

Given the already implemented RAG logic (retrieval+generation) in rag_chain.py, this script:
- imports the existing pipeline functions from the local modules
- wraps them in a small FastAPI HTTP service
- expose a /chat endpoint that calls the same chain used locally

"""

import os
import logging

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel # interface to define request and response body schemas

# Local pipeline modules (same as used in the local notebook / scripts)
from rag_chain import build_chain
from store import get_embeddings, get_vector_store, get_retriever
from config import CONFIG, resolve_mongo_cfg

### Logging setup
logging.basicConfig(level=logging.INFO)
logger=logging.getLogger("smartstudy-chat")

### FastAPI app
app=FastAPI(
    title="SmartStudy Chat",
    description="Thin API wrapper around the local RAG chain for Cloud Run deployment.",)

# # Global variable that will hold the RAG chain after startup. We build it once at startup so we don't re-load models
# _chain=None

# @app.on_event("startup")
# def load_chain():
#     """Build the RAG chain once when the container starts.
#     This function:
#     1. creates the embeddings model
#     2. Connects to the vector store (MongoDB)
#     3. Creates the retriever
#     4. Builds the full RAG chain (retrieval+generation)
#     """

#     global _chain
#     logger.info("Building RAG chain at startup...")

#     # 1. Embedding model
#     embeddings = get_embeddings(CONFIG["embedding"]["model"])

#     # 2. Vector store (MongoDB)
#     vector_store = get_vector_store(resolve_mongo_cfg(CONFIG), embeddings)

#     # 3. Retriever
#     retriever = get_retriever(vector_store, k=CONFIG["retrieval"]["k"])

#     # 4. Full RAG chain: retriever + LLM + prompt
#     chain = build_chain(retriever, CONFIG["generation"]["model"], temperature=CONFIG["generation"].get("temperature", 0.2),)

#     logger.info("Chain ready.")

logger.info("Building RAG chain...")
_embeddings = get_embeddings(CONFIG["embedding"]["model"])
_vector_store = get_vector_store(resolve_mongo_cfg(CONFIG), _embeddings)
_retriever = get_retriever(_vector_store, k=CONFIG["retrieval"]["k"])
_chain = build_chain(
    _retriever,
    CONFIG["generation"]["model"],
    temperature=CONFIG["generation"].get("temperature", 0.2),
)
logger.info("Chain ready.")

### Request/Response models
class ChatRequest(BaseModel):
    """Request body for éPST /chat.
    
    Fields:
    - query: the user's question
    - history: optional conversation history
    """

    query:str
    #history:list[dict]|None=None

class ChatResponse(BaseModel):
    """Response body for POST /chat.
    
    Field: - answer: the text answer generated by the RAG chain"""
    answer:str

### API endpoints

@app.post("/chat", response_model=ChatResponse)
def chat(req: ChatRequest):
    """Handle a chat request.
    Steps:
    1. Check that the chain has being initialized at startup.
    2. Log a warning if history is provided
    3. Call the RAG chain with the user's query
    4. Return the answer as JSON
    
    If error: return a 500 error with the exception message """

    if _chain is None:
        raise HTTPException(status_code=500, detail="Chain not initialized yet")

    # if req.history:
    #     logger.warning("history received but not used by chain")

    try:
        # invoke the RAG chain with the user's question
        answer=_chain.invoke(req.query)
    except Exception as e:
        logger.exception("Chain invocation failed")
        raise HTTPException(status_code=500, details=str(e))
    return ChatResponse(answer=answer)

@app.get("/health")
def health():
    """
    Health check endpoint.

    Used by Cloud Run / load balancers to verify the service is alive
    and whether the RAG chain is ready.

    Returns:
      {
        "status": "ok",
        "chain_ready": true/false
      }
    """
    return {"status": "ok", "chain_ready": _chain is not None}